"""Neubau -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/neubau.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Neubau')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (16.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (16.35, 0.15), (16.35, 9.35), thickness=0.3, external=True)
eg.wall('EXT-N', (16.35, 9.35), (0.15, 9.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (12.3, 5.4), (14.6, 5.4), thickness=0.15)
eg.wall('INT-2', (14.6, 5.4), (14.6, 9.35), thickness=0.15)
eg.wall('INT-3', (12.3, 5.4), (12.3, 9.35), thickness=0.15)
eg.wall('INT-4', (5.35, 5.4), (5.35, 9.35), thickness=0.15)
eg.wall('INT-5', (5.35, 5.4), (8.85, 5.4), thickness=0.15)
eg.wall('INT-6', (8.85, 5.4), (8.85, 9.35), thickness=0.15)
eg.wall('INT-7', (0.15, 5.4), (5.35, 5.4), thickness=0.15)
eg.wall('INT-8', (0.15, 4.1), (16.35, 4.1), thickness=0.15)
eg.wall('INT-9', (14.6, 5.4), (16.35, 5.4), thickness=0.15)
eg.wall('INT-10', (8.85, 5.4), (12.3, 5.4), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Bad', [(12.4, 5.5), (14.5, 5.5), (14.5, 9.2), (12.4, 9.2)])   # R-01 9.1 m2 target 8.0
eg.room('Küche', [(5.4, 5.5), (8.75, 5.5), (8.75, 9.2), (5.4, 9.2)])   # R-02 13.8 m2 target 12.0
eg.room('Besprechung', [(0.3, 5.5), (5.25, 5.5), (5.25, 9.2), (0.3, 9.2)])   # R-03 20.5 m2 target 18.0
eg.room('Büro', [(0.3, 0.3), (16.2, 0.3), (16.2, 4.0), (0.3, 4.0)])   # R-04 64.0 m2 target 60.0
eg.room('Flur', [(0.3, 4.15), (16.2, 4.15), (16.2, 5.35), (0.3, 5.35)])   # R-05 21.1 m2 target 10.0
eg.room('HWR', [(14.65, 5.5), (16.2, 5.5), (16.2, 9.2), (14.65, 9.2)])   # R-06 6.9 m2 target 6.0
eg.room('Stair', [(8.9, 5.5), (12.2, 5.5), (12.2, 9.2), (8.9, 9.2)])   # R-07 13.6 m2 target 12.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=8.1, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=1.15, width=0.8, height=2.05)   # R-05 <-> R-01
eg.door('D-02', on='INT-5', at=1.75, width=0.8, height=2.05)   # R-05 <-> R-02
eg.door('D-03', on='INT-7', at=2.6, width=0.8, height=2.05)   # R-05 <-> R-03
eg.door('D-04', on='INT-8', at=8.1, width=0.8, height=2.05)   # R-05 <-> R-04
eg.door('D-05', on='INT-9', at=0.9, width=0.8, height=2.05)   # R-05 <-> R-06
eg.door('D-06', on='INT-10', at=1.75, width=0.8, height=2.05)   # R-05 <-> R-07

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-N', at=9.25, width=1.25, height=1.4, sill=0.9)   # R-02 needs 1.73 m2
eg.window('F-02', on='EXT-S', at=4.7, width=5.7, height=1.4, sill=0.9)   # R-04 needs 8.00 m2

if __name__ == "__main__":
    h.write("out/neubau/model.ifc")

