"""Dreifamilienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/dreifamilienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Dreifamilienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (10.85, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (10.85, 0.15), (10.85, 9.35), thickness=0.3, external=True)
eg.wall('EXT-N', (10.85, 9.35), (0.15, 9.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (7.45, 0.15), (7.45, 4.1), thickness=0.15)
eg.wall('INT-2', (0.15, 4.1), (7.45, 4.1), thickness=0.15)
eg.wall('INT-3', (7.45, 4.1), (10.85, 4.1), thickness=0.15)
eg.wall('INT-4', (4.3, 5.4), (4.3, 9.35), thickness=0.15)
eg.wall('INT-5', (0.15, 5.4), (4.3, 5.4), thickness=0.15)
eg.wall('INT-6', (8.45, 5.4), (8.45, 9.35), thickness=0.15)
eg.wall('INT-7', (4.3, 5.4), (8.45, 5.4), thickness=0.15)
eg.wall('INT-8', (8.45, 5.4), (10.85, 5.4), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (7.35, 0.3), (7.35, 4.0), (0.3, 4.0)])   # R-01 28.8 m2 target 26.0
eg.room('Küche', [(7.5, 0.3), (10.7, 0.3), (10.7, 4.0), (7.5, 4.0)])   # R-02 13.4 m2 target 12.0
eg.room('Schlafzimmer 1', [(0.3, 5.5), (4.2, 5.5), (4.2, 9.2), (0.3, 9.2)])   # R-03 16.4 m2 target 14.0
eg.room('Schlafzimmer 2', [(4.4, 5.5), (8.4, 5.5), (8.4, 9.2), (4.4, 9.2)])   # R-04 16.4 m2 target 14.0
eg.room('Bad', [(8.5, 5.5), (10.7, 5.5), (10.7, 9.2), (8.5, 9.2)])   # R-05 9.5 m2 target 8.0
eg.room('Flur', [(0.3, 4.15), (10.7, 4.15), (10.7, 5.35), (0.3, 5.35)])   # R-06 13.9 m2 target 10.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=5.35, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=3.65, width=0.8, height=2.05)   # R-06 <-> R-01
eg.door('D-02', on='INT-3', at=1.7, width=0.8, height=2.05)   # R-06 <-> R-02
eg.door('D-03', on='INT-5', at=2.05, width=0.8, height=2.05)   # R-06 <-> R-03
eg.door('D-04', on='INT-7', at=2.05, width=0.8, height=2.05)   # R-06 <-> R-04
eg.door('D-05', on='INT-8', at=1.2, width=0.8, height=2.05)   # R-06 <-> R-05

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=3.5, width=2.55, height=1.4, sill=0.9)   # R-01 needs 3.60 m2
eg.window('F-02', on='EXT-E', at=1.95, width=1.2, height=1.4, sill=0.9)   # R-02 needs 1.68 m2
eg.window('F-03', on='EXT-N', at=8.6, width=1.45, height=1.4, sill=0.9)   # R-03 needs 2.05 m2
eg.window('F-04', on='EXT-N', at=4.45, width=1.45, height=1.4, sill=0.9)   # R-04 needs 2.05 m2

if __name__ == "__main__":
    h.write("out/dreifamilienhaus/model.ifc")

