"""Coworking Studio -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/coworking-studio.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Coworking Studio')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.7)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (14.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (14.35, 0.15), (14.35, 8.35), thickness=0.3, external=True)
eg.wall('EXT-N', (14.35, 8.35), (0.15, 8.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 8.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (0.15, 3.55), (14.35, 3.55), thickness=0.15)
eg.wall('INT-2', (6.9, 4.9), (6.9, 8.35), thickness=0.15)
eg.wall('INT-3', (0.15, 4.9), (6.9, 4.9), thickness=0.15)
eg.wall('INT-4', (11.35, 4.9), (11.35, 8.35), thickness=0.15)
eg.wall('INT-5', (11.35, 4.9), (14.35, 4.9), thickness=0.15)
eg.wall('INT-6', (6.9, 4.9), (11.35, 4.9), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Studio', [(0.3, 0.3), (14.2, 0.3), (14.2, 3.45), (0.3, 3.45)])   # R-01 48.3 m2 target 50.0
eg.room('Conference', [(0.3, 5.0), (6.8, 5.0), (6.8, 8.2), (0.3, 8.2)])   # R-02 23.3 m2 target 18.0
eg.room('Washroom', [(11.4, 5.0), (14.2, 5.0), (14.2, 8.2), (11.4, 8.2)])   # R-03 10.3 m2 target 8.0
eg.room('Kitchenette', [(7.0, 5.0), (11.25, 5.0), (11.25, 8.2), (7.0, 8.2)])   # R-04 15.4 m2 target 12.0
eg.room('Flur', [(0.3, 3.6), (14.2, 3.6), (14.2, 4.85), (0.3, 4.85)])   # R-05 19.2 m2 target 10.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=7.1, width=1.01, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=7.1, width=0.885, height=2.05)   # R-05 <-> R-01
eg.door('D-02', on='INT-3', at=3.4, width=0.885, height=2.05)   # R-05 <-> R-02
eg.door('D-03', on='INT-5', at=1.5, width=0.885, height=2.05)   # R-05 <-> R-03
eg.door('D-04', on='INT-6', at=2.2, width=0.885, height=2.05)   # R-05 <-> R-04

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=4.35, width=4.3, height=1.4, sill=0.9)   # R-01 needs 6.03 m2
eg.window('F-02', on='EXT-N', at=5.2, width=1.35, height=1.4, sill=0.9)   # R-04 needs 1.92 m2

if __name__ == "__main__":
    h.write("out/coworking-studio/model.ifc")

