"""Coworking Studio -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/coworking-studio.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Coworking Studio')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.7)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (12.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (12.35, 0.15), (12.35, 9.35), thickness=0.3, external=True)
eg.wall('EXT-N', (12.35, 9.35), (0.15, 9.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (7.1, 0.15), (7.1, 4.5), thickness=0.15)
eg.wall('INT-2', (7.1, 4.5), (7.1, 9.35), thickness=0.15)
eg.wall('INT-3', (7.1, 4.5), (9.2, 4.5), thickness=0.15)
eg.wall('INT-4', (9.2, 4.5), (12.35, 4.5), thickness=0.15)
eg.wall('INT-5', (9.2, 4.5), (9.2, 9.35), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Studio', [(0.3, 0.3), (7.0, 0.3), (7.0, 9.2), (0.3, 9.2)])   # R-01 63.9 m2 target 56.0
eg.room('Conference', [(7.2, 0.3), (12.2, 0.3), (12.2, 4.4), (7.2, 4.4)])   # R-02 22.8 m2 target 20.2
eg.room('Washroom', [(7.2, 4.6), (9.1, 4.6), (9.1, 9.2), (7.2, 9.2)])   # R-03 10.2 m2 target 9.0
eg.room('Kitchenette', [(9.25, 4.6), (12.2, 4.6), (12.2, 9.2), (9.25, 9.2)])   # R-04 15.3 m2 target 13.4

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=6.1, width=1.01, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=2.15, width=0.885, height=2.05)   # R-01 <-> R-02
eg.door('D-02', on='INT-2', at=2.4, width=0.885, height=2.05)   # R-01 <-> R-03
eg.door('D-03', on='INT-5', at=2.4, width=0.885, height=2.05)   # R-03 <-> R-04  (plan asked for R-01; rerouted to the neighbour it touches)

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-W', at=4.6, width=5.7, height=1.4, sill=0.9)   # R-01 needs 7.99 m2
eg.window('F-02', on='EXT-E', at=6.75, width=1.35, height=1.4, sill=0.9)   # R-04 needs 1.91 m2

if __name__ == "__main__":
    h.write("out/coworking-studio/model.ifc")

