"""The autonomous layer: one trigger in, merged artifacts out, nobody in between.

    brief ──▶ N candidate strategies ──▶ build each ──▶ verify each
                                                          │
                        merge the winner ◀── rank ◀───────┘

The human is at the *trigger*, never inside the run. Once a brief is sealed the
loop runs to a merged pull request with no approval step: the deterministic
verifier in `recognition.score` is the only gate, and `score.rank` -- not a person
and not a model -- picks which candidate wins.

Two candidate engines, same interface:

* ``local``  -- strategies are generated by deterministic heuristics here. Fast,
  free, always available; used for tests and as the fallback when Devin is
  unreachable. This is what makes the system demonstrable without burning ACU.
* ``devin``  -- each strategy becomes its own Devin session, working in the repo,
  running the verifier on itself, and pushing a branch. Slower, and the real
  product: the sessions do the engineering.

A run is reproducible: the same brief and the same strategy set produce the same
buildings, because everything between the plan and the artifacts is deterministic.
"""
from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from .contracts import ArchitectPlan, Adjacency, DesignBrief, Envelope, RoomSpec
from .score import Verdict, load_ruleset, rank, verdict, winner
from .translate import LayoutError, translate_to_file

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RULES = REPO_ROOT / "rules" / "by" / "residential.yaml"


# --------------------------------------------------------------------------
# Strategies -- how sibling candidates differ
# --------------------------------------------------------------------------

@dataclass
class Strategy:
    """One way to satisfy the same brief.

    Candidates must differ *structurally*, not by random seed, or the fan-out is
    theatre: three sessions producing the same building prove nothing.
    """
    name: str
    label: str
    description: str
    aspect: float = 1.2          # envelope width : depth
    circulation: bool = True     # a dedicated hall spine, or rooms opening directly
    generosity: float = 1.0      # multiplier on requested room areas


STRATEGIES: list[Strategy] = [
    Strategy("compact", "Compact core",
             "Squarer envelope with a central hall spine. Least external wall per "
             "m2, so cheapest to build and to heat.",
             aspect=1.15, circulation=True, generosity=1.0),
    Strategy("linear", "Linear frontage",
             "Wider, shallower envelope. Every habitable room reaches an exterior "
             "wall, which makes the daylight rule easy to satisfy.",
             aspect=1.75, circulation=True, generosity=1.0),
    Strategy("open", "Open plan",
             "No dedicated corridor; living spaces connect directly. Converts "
             "circulation area into usable floor.",
             aspect=1.35, circulation=False, generosity=1.12),
]


def strategy_by_name(name: str) -> Strategy:
    for s in STRATEGIES:
        if s.name == name:
            return s
    raise KeyError(f"unknown strategy '{name}'; have {[s.name for s in STRATEGIES]}")


# --------------------------------------------------------------------------
# Brief -> ArchitectPlan (the `local` candidate engine)
# --------------------------------------------------------------------------

DEFAULT_AREAS = {          # Richtwerte, guidance tier -- never presented as law
    "living": 26.0, "kitchen": 12.0, "bedroom": 14.0, "bathroom": 8.0,
    "office": 12.0, "hall": 10.0, "utility": 6.0, "other": 10.0,
}


def plan_from_brief(brief: DesignBrief, strat: Strategy) -> ArchitectPlan:
    """Deterministically expand a brief into a plan under one strategy.

    No model is called. Room areas come from the brief where the client gave
    them and from published Richtwerte otherwise -- and because those are
    guidance, not law, the compliance gate will never block on them.
    """
    rooms: list[RoomSpec] = []
    n = 0
    for req in brief.rooms:
        for i in range(req.count):
            n += 1
            base = req.min_area_m2 or DEFAULT_AREAS.get(req.category, 12.0)
            label = req.label or _german(req.category)
            if req.count > 1:
                label = f"{label} {i + 1}"
            rooms.append(RoomSpec(
                id=f"R-{n:02d}", category=req.category, label=label,
                target_area_m2=round(base * strat.generosity, 1),
            ))

    hall_id: str | None = None
    if strat.circulation and not any(r.category == "hall" for r in rooms):
        n += 1
        hall_id = f"R-{n:02d}"
        rooms.append(RoomSpec(hall_id, "hall", "Flur",
                              round(DEFAULT_AREAS["hall"] * strat.generosity, 1)))
    elif strat.circulation:
        hall_id = next(r.id for r in rooms if r.category == "hall")

    # Envelope sized from the programme plus a circulation and wall allowance,
    # then shaped by the strategy's aspect ratio.
    need = sum(r.target_area_m2 for r in rooms) * 1.22
    depth = (need / strat.aspect) ** 0.5
    width = need / depth
    env = Envelope(width_m=round(width * 2) / 2, depth_m=round(depth * 2) / 2)

    adjacency = _adjacencies(rooms, hall_id)
    return ArchitectPlan(
        project=brief.project, envelope=env, rooms=rooms, adjacency=adjacency,
        storey_height_m=brief.storey_height_m, circulation_id=hall_id,
        accessibility_tier=brief.accessibility_tier,
        rationale=f"{strat.label}: {strat.description}",
    )


def _adjacencies(rooms: list[RoomSpec], hall_id: str | None) -> list[Adjacency]:
    """Everything opens off the hall; without one, chain through the living room.

    A bathroom is never reached through a bedroom -- that is the convention this
    codifies, and it is why adjacency is declared rather than inferred later.
    """
    if hall_id:
        return [Adjacency(hall_id, r.id) for r in rooms if r.id != hall_id]
    anchor = next((r for r in rooms if r.category == "living"), rooms[0])
    return [Adjacency(anchor.id, r.id) for r in rooms if r.id != anchor.id]


def _german(category: str) -> str:
    return {"living": "Wohnen", "kitchen": "Küche", "bedroom": "Schlafzimmer",
            "bathroom": "Bad", "office": "Büro", "hall": "Flur",
            "utility": "HWR", "other": "Raum"}.get(category, category.title())


# --------------------------------------------------------------------------
# Build + verify one candidate
# --------------------------------------------------------------------------

@dataclass
class Candidate:
    name: str
    label: str
    plan: ArchitectPlan | None = None
    out_dir: Path | None = None
    verdict: Verdict | None = None
    error: str = ""
    devin_session: str = ""
    pull_request: str = ""

    @property
    def ok(self) -> bool:
        return self.verdict is not None and self.verdict.ok

    def summary(self) -> dict[str, Any]:
        return {
            "name": self.name, "label": self.label,
            "ok": self.ok, "error": self.error,
            "devin_session": self.devin_session, "pull_request": self.pull_request,
            "verdict": self.verdict.to_dict() if self.verdict else None,
        }


def build_and_verify(plan: ArchitectPlan, out_dir: Path, *, name: str,
                     rules_path: Path = DEFAULT_RULES,
                     brief: DesignBrief | None = None,
                     viewable: bool = True) -> Verdict:
    """Plan -> DSL -> IFC -> compliance verdict. Every step deterministic.

    With `viewable`, also renders the sheets and the 3D mesh the Studio needs.
    Tests turn it off: geometry is the thing under test, rendering is not.
    """
    import recognition.model as M
    import recognition.rules as R

    out_dir.mkdir(parents=True, exist_ok=True)
    plan.write(out_dir / "plan.json")

    dsl = translate_to_file(plan, out_dir / "design.py")           # L3: zero tokens
    ifc_path = out_dir / "model.ifc"
    _exec_dsl(dsl, ifc_path)                                       # L4: geometry

    model = M.load(ifc_path)                                       # L5: the gate
    report = R.check(model, R.load_ruleset(rules_path))
    _doc, metas = load_ruleset(rules_path)

    v = verdict(report, metas, candidate=name,
                brief=(brief.to_dict() if brief else None),
                metrics=_metrics(plan, model))
    v.write(out_dir / "verdict.json")

    if viewable:
        _viewables(ifc_path, out_dir, plan.project, rules_path)
    return v


def _viewables(ifc_path: Path, out_dir: Path, project: str, rules_path: Path) -> None:
    """Sheets and the 3D mesh: everything a person needs to judge the result.

    Best-effort by design. A candidate is legal or not on the strength of its
    compliance verdict; a missing PNG must never turn a passing building into a
    failing one, so rendering problems are reported and swallowed.
    """
    from . import mesh
    from .cli import run as run_package
    try:
        run_package(ifc_path, out_dir / "pkg", rules_path, project, "")
    except Exception as e:                      # noqa: BLE001 - presentation only
        print(f"      (sheets unavailable: {type(e).__name__}: {str(e)[:90]})")
    try:
        mesh.write(ifc_path, out_dir / "mesh.json")
    except Exception as e:                      # noqa: BLE001 - presentation only
        print(f"      (3D mesh unavailable: {type(e).__name__}: {str(e)[:90]})")


def _exec_dsl(dsl_path: Path, ifc_path: Path) -> None:
    """Run the generated module in a subprocess so a bad candidate cannot take
    the orchestrator down with it."""
    ifc_path.parent.mkdir(parents=True, exist_ok=True)
    code = (
        f"import runpy,sys;"
        f"ns=runpy.run_path({str(dsl_path)!r});"
        f"ns['h'].write({str(ifc_path)!r})"
    )
    proc = subprocess.run([sys.executable, "-c", code], cwd=REPO_ROOT,
                          capture_output=True, text=True, timeout=300)
    if proc.returncode != 0 or not ifc_path.exists():
        raise RuntimeError(
            f"generated design failed to build an IFC:\n{proc.stderr[-1500:]}"
        )


def _metrics(plan: ArchitectPlan, model) -> dict[str, Any]:
    """Ranking inputs. Cheap, geometric, and free of judgement."""
    room_area = sum(s.area for s in model.spaces)
    circ = sum(s.area for s in model.spaces if s.category == "hall")
    env = plan.envelope.area_m2
    return {
        "envelope_m2": round(env, 2),
        "room_area_m2": round(room_area, 2),
        "usable_ratio": round((room_area - circ) / env, 4) if env else 0.0,
        "circulation_m2": round(circ, 2),
        "openings": len(model.doors) + len(model.windows),
        "rooms": len(model.spaces),
    }


# --------------------------------------------------------------------------
# The run
# --------------------------------------------------------------------------

@dataclass
class RunResult:
    project: str
    engine: str
    candidates: list[Candidate] = field(default_factory=list)
    winner: str = ""
    merged: str = ""
    critic: str = ""

    def to_dict(self) -> dict:
        return {
            "project": self.project, "engine": self.engine,
            "winner": self.winner, "merged": self.merged, "critic": self.critic,
            "candidates": [c.summary() for c in self.candidates],
        }

    def write(self, path: str | Path) -> Path:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(self.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")
        return p


def run_local(brief: DesignBrief, out_root: Path, *, strategies: list[Strategy] | None = None,
              rules_path: Path = DEFAULT_RULES, log=print) -> RunResult:
    """The full loop with deterministic candidate generation. No API, no cost."""
    brief.resolve_accessibility()
    brief.validate()
    strats = strategies or STRATEGIES
    res = RunResult(project=brief.project, engine="local")

    for strat in strats:
        c = Candidate(strat.name, strat.label)
        log(f"  · {strat.name}: {strat.description[:64]}…")
        try:
            plan = plan_from_brief(brief, strat)
            c.plan = plan
            c.out_dir = out_root / strat.name
            c.verdict = build_and_verify(plan, c.out_dir, name=strat.name,
                                         rules_path=rules_path, brief=brief)
            log(f"    {c.verdict.stamp()} — {c.verdict.coverage_line()}")
        except (LayoutError, RuntimeError, ValueError) as e:
            # A candidate that cannot be built is a legitimate outcome of
            # exploration, not a crash. Record it and keep the siblings running.
            c.error = f"{type(e).__name__}: {e}"
            log(f"    unbuildable — {c.error[:110]}")
        res.candidates.append(c)

    verdicts = [c.verdict for c in res.candidates if c.verdict]
    best = winner(verdicts)
    if best:
        res.winner = best.candidate
        log(f"\n  winner: {best.candidate} ({best.coverage_line()}) — chosen by the scorer, not a human")
    else:
        log("\n  no candidate passed the compliance gate")
    res.write(out_root / "run.json")
    return res


def ranked(res: RunResult) -> list[Verdict]:
    return rank([c.verdict for c in res.candidates if c.verdict])


# --------------------------------------------------------------------------
# The Devin engine
# --------------------------------------------------------------------------

BUILDER_PROMPT = """\
You are the architect on a Bayern residential project. Produce ONE floor-plan
layout as an ArchitectPlan JSON object and return it via the structured output
tool. Do not write code, do not open a pull request, and do not push anything.

STRATEGY YOU MUST FOLLOW — "{label}"
{description}
Your sibling sessions are exploring different strategies. Yours must be
structurally distinct from theirs, not a variation in numbers.

THE BRIEF
{brief}

THE SHAPE YOU MUST RETURN — ArchitectPlan
  envelope: {{width_m, depth_m, external_wall_m: 0.30, internal_wall_m: 0.15}}
  rooms:    [{{id: "R-01", category, label, target_area_m2, exterior_wall}}]
  adjacency:[{{a: "R-03", b: "R-01", via: "door"}}]
  circulation_id: the id of the hall room, or null for an open plan
  storey_height_m, accessibility_tier, rationale

HARD CONSTRAINTS — a plan breaking any of these is rejected automatically
1. NO COORDINATES. Give areas and adjacencies only. Wall positions are computed
   downstream by deterministic code; anything you invent there is discarded.
2. category must be one of: bedroom, living, kitchen, bathroom, office, hall,
   utility, other.
3. Every room must be reachable: the adjacency graph must be connected. A
   bathroom is never reached through a bedroom.
4. Sum of target_area_m2 must fit the envelope with ~22% left for walls and
   circulation, or the plan is infeasible and will be thrown away.
5. Every habitable room (bedroom, living, kitchen, office) needs an exterior
   wall — BayBO Art. 45 (2) requires glazing of 1/8 of its floor area.
6. Do not quote or invent a building regulation. Compliance is judged by a
   deterministic engine against a cited ruleset; your job is the layout.

Return only the JSON object.
"""

CRITIC_PROMPT = """\
You are reviewing a floor plan that has already passed an automated compliance
gate. Assume the numbers are right; look for what a checker cannot see.

THE PLAN
{plan}

THE COMPLIANCE RESULT
{verdict}

Answer strictly as JSON: {{"verdict": "PASS"|"FAIL", "notes": "<your review>"}}
where FAIL means you found something that makes this unbuildable or unfit to
live in — a room you cannot furnish, a door that would swing into another, a
circulation route that does not work, an orientation that wastes the site.
Be specific and brief. Do not restate the compliance result back to me.
"""


def run_devin(brief: DesignBrief, out_root: Path, *,
              strategies: list[Strategy] | None = None,
              rules_path: Path = DEFAULT_RULES,
              max_acu: int | None = None, timeout_s: float = 1800,
              critic: bool = True, log=print) -> RunResult:
    """The real product: N Devin sessions plan in parallel, we build and judge.

    Devin returns an ArchitectPlan and never touches the repository. That is not
    a workaround for the missing write permission -- it is the safer split. The
    session cannot report its own success, because the artifacts it is judged on
    are produced here, by deterministic code, from the plan it handed back.
    """
    from .devin import DevinClient, SessionSpec, fan_out, wait_all

    brief.resolve_accessibility()
    brief.validate()
    strats = strategies or STRATEGIES
    res = RunResult(project=brief.project, engine="devin")
    client = DevinClient()

    brief_json = json.dumps(brief.to_dict(), indent=2, ensure_ascii=False)
    specs = [
        SessionSpec(
            name=s.name, strategy=s.name,
            prompt=BUILDER_PROMPT.format(label=s.label, description=s.description,
                                         brief=brief_json),
            tags=["recognition", "autopilot", f"strategy:{s.name}"],
            max_acu=max_acu,
        )
        for s in strats
    ]

    log(f"  starting {len(specs)} Devin sessions in parallel…")
    ids = fan_out(client, specs, structured_output=_plan_schema())
    for name, sid in ids.items():
        log(f"    {name:9} → {sid or 'FAILED TO START'}")

    def _tick(name: str, snap) -> None:
        log(f"    {name:9} … {snap.status}")

    results = wait_all(client, ids, timeout_s=timeout_s, on_update=_tick)

    for s in strats:
        c = Candidate(s.name, s.label)
        r = results.get(s.name)
        c.devin_session = r.session_id if r else ""
        if r is None or not r.produced_output:
            c.error = (r.error if r else "no result") or f"session ended in '{r.status}' with no plan"
            log(f"  · {s.name}: {c.error[:110]}")
            res.candidates.append(c)
            continue
        try:
            plan, out = _plan_with_repair(client, r, brief, s, timeout_s, log=log)
            c.plan = plan
            c.out_dir = out_root / s.name
            c.verdict = build_and_verify(plan, c.out_dir, name=s.name,
                                         rules_path=rules_path, brief=brief)
            log(f"  · {s.name}: {c.verdict.stamp()} — {c.verdict.coverage_line()}")
        except (LayoutError, RuntimeError, ValueError) as e:
            c.error = f"{type(e).__name__}: {e}"
            log(f"  · {s.name}: unbuildable — {c.error[:110]}")
        res.candidates.append(c)

    best = winner([c.verdict for c in res.candidates if c.verdict])
    if best:
        res.winner = best.candidate
        log(f"\n  winner: {best.candidate} — chosen by the scorer, not a human")
        if critic:
            res.critic = _run_critic(client, res, best, log=log)
    else:
        log("\n  no candidate passed the compliance gate")

    client.close()
    res.write(out_root / "run.json")
    return res


def _plan_with_repair(client, result, brief: DesignBrief, strat: Strategy,
                      timeout_s: float, *, attempts: int = 2, log=print) -> tuple[ArchitectPlan, dict]:
    """Validate the session's plan; on a contract error, hand the error back.

    This is the whole autonomy argument in miniature. The validator's message is
    written to be an instruction ("room R-04 target_area_m2 must be > 0"), so the
    session can repair itself without a human reading the traceback. No person
    sees this loop unless every attempt fails.
    """
    from .contracts import ContractError
    from .devin import wait_all

    payload = result.structured_output
    last_err = ""
    for attempt in range(1, attempts + 1):
        try:
            return _plan_from_output(payload, brief, strat, log=log), payload
        except ContractError as e:
            last_err = str(e)
            if attempt == attempts:
                break
            log(f"    {strat.name}: contract error, asking the session to repair "
                f"(attempt {attempt}/{attempts - 1})")
            log(f"      {last_err[:150]}")
            try:
                client.send_message(
                    result.session_id,
                    f"The plan you returned was rejected by the schema validator:\n\n"
                    f"  {last_err}\n\n"
                    f"Return the corrected ArchitectPlan JSON object only. Change nothing "
                    f"except what the error names."
                )
            except Exception as e2:            # noqa: BLE001 - repair is best effort
                log(f"      could not send repair request: {e2}")
                break
            nxt = wait_all(client, {strat.name: result.session_id},
                           timeout_s=min(timeout_s, 600)).get(strat.name)
            if not nxt or not nxt.structured_output:
                break
            payload = nxt.structured_output
    raise ValueError(f"plan rejected after {attempts} attempt(s): {last_err}")


def _plan_schema() -> dict:
    """The structured-output contract handed to every builder session."""
    return {
        "type": "object",
        "properties": {
            "envelope": {"type": "object"},
            "rooms": {"type": "array"},
            "adjacency": {"type": "array"},
            "circulation_id": {"type": ["string", "null"]},
            "storey_height_m": {"type": "number"},
            "accessibility_tier": {"type": "string"},
            "rationale": {"type": "string"},
        },
        "required": ["envelope", "rooms"],
    }


# Synonyms observed from real sessions. Normalising these is being liberal about
# vocabulary, not about meaning: each maps to exactly one term with no ambiguity.
# Anything genuinely wrong still fails validation and goes back for repair.
_VIA_SYNONYMS = {"opening": "open", "open_plan": "open", "openplan": "open",
                 "direct": "open", "doorway": "door", "passage": "open"}
_CATEGORY_SYNONYMS = {
    "bath": "bathroom", "wc": "bathroom", "toilet": "bathroom", "shower": "bathroom",
    "bed": "bedroom", "bedrooms": "bedroom", "sleeping": "bedroom",
    "livingroom": "living", "living_room": "living", "lounge": "living", "dining": "living",
    "corridor": "hall", "hallway": "hall", "flur": "hall", "circulation": "hall",
    "study": "office", "workroom": "office",
    "storage": "utility", "technical": "utility", "laundry": "utility", "hwr": "utility",
}


def normalise_agent_plan(payload: dict) -> tuple[dict, list[str]]:
    """Map known vocabulary variants onto the contract's terms.

    Returns the payload plus a list of what was rewritten, so normalisation is
    visible in the run log rather than being a silent correction.
    """
    notes: list[str] = []
    for a in payload.get("adjacency", []) or []:
        if not isinstance(a, dict):
            continue
        via = str(a.get("via", "door")).strip().lower()
        if via in _VIA_SYNONYMS:
            notes.append(f"adjacency via '{via}' → '{_VIA_SYNONYMS[via]}'")
            a["via"] = _VIA_SYNONYMS[via]
    for r in payload.get("rooms", []) or []:
        if not isinstance(r, dict):
            continue
        cat = str(r.get("category", "")).strip().lower().replace(" ", "_")
        if cat in _CATEGORY_SYNONYMS:
            notes.append(f"room {r.get('id')} category '{cat}' → '{_CATEGORY_SYNONYMS[cat]}'")
            r["category"] = _CATEGORY_SYNONYMS[cat]
        elif cat:
            r["category"] = cat
    return payload, notes


def _plan_from_output(out: dict, brief: DesignBrief, strat: Strategy,
                      log=None) -> ArchitectPlan:
    """Validate whatever the session returned. Never trust it unchecked."""
    from .contracts import load_plan
    payload = dict(out)
    payload.setdefault("project", brief.project)
    payload.setdefault("storey_height_m", brief.storey_height_m)
    payload.setdefault("accessibility_tier", brief.accessibility_tier)
    payload.setdefault("rationale", f"{strat.label}: {strat.description}")
    payload.pop("schema", None)
    payload, notes = normalise_agent_plan(payload)
    if notes and log:
        for n in notes:
            log(f"      normalised: {n}")
    return load_plan(payload)


def _run_critic(client, res: RunResult, best: Verdict, *, log=print) -> str:
    """A fourth session that reviews what the checker cannot see.

    Advisory by construction: it can annotate the winner, never overturn it. A
    model must not be able to veto a deterministic gate, in either direction.
    """
    from .devin import wait_all
    cand = next((c for c in res.candidates if c.verdict is best), None)
    if cand is None or cand.plan is None:
        return ""
    log("  critic: reviewing the winner…")
    try:
        sid = client.create_session(
            CRITIC_PROMPT.format(
                plan=json.dumps(cand.plan.to_dict(), indent=2, ensure_ascii=False)[:6000],
                verdict=json.dumps(best.to_dict()["findings"][:10], indent=2)[:3000],
            ),
            title=f"Recognition · critic · {res.project}",
            tags=["recognition", "autopilot", "critic"],
            structured_output={"type": "object",
                               "properties": {"verdict": {"type": "string"},
                                              "notes": {"type": "string"}},
                               "required": ["verdict", "notes"]},
        )
    except Exception as e:                     # noqa: BLE001 - advisory stage
        log(f"  critic unavailable: {e}")
        return ""
    out = wait_all(client, {"critic": sid}, timeout_s=900).get("critic")
    if out and out.structured_output:
        note = str(out.structured_output.get("notes", ""))[:1200]
        log(f"  critic says: {note[:160]}")
        return note
    return ""
