"""Dreifamilienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/dreifamilienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Dreifamilienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (13.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (13.35, 0.15), (13.35, 7.35), thickness=0.3, external=True)
eg.wall('EXT-N', (13.35, 7.35), (0.15, 7.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 7.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (9.2, 0.15), (9.2, 3.1), thickness=0.15)
eg.wall('INT-2', (0.15, 3.1), (9.2, 3.1), thickness=0.15)
eg.wall('INT-3', (9.2, 3.1), (13.35, 3.1), thickness=0.15)
eg.wall('INT-4', (5.3, 4.4), (5.3, 7.35), thickness=0.15)
eg.wall('INT-5', (0.15, 4.4), (5.3, 4.4), thickness=0.15)
eg.wall('INT-6', (10.4, 4.4), (10.4, 7.35), thickness=0.15)
eg.wall('INT-7', (5.3, 4.4), (10.4, 4.4), thickness=0.15)
eg.wall('INT-8', (10.4, 4.4), (13.35, 4.4), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (9.1, 0.3), (9.1, 3.0), (0.3, 3.0)])   # R-01 26.7 m2 target 26.0
eg.room('Küche', [(9.25, 0.3), (13.2, 0.3), (13.2, 3.0), (9.25, 3.0)])   # R-02 12.2 m2 target 12.0
eg.room('Schlafzimmer 1', [(0.3, 4.5), (5.2, 4.5), (5.2, 7.2), (0.3, 7.2)])   # R-03 15.2 m2 target 14.0
eg.room('Schlafzimmer 2', [(5.4, 4.5), (10.3, 4.5), (10.3, 7.2), (5.4, 7.2)])   # R-04 15.0 m2 target 14.0
eg.room('Bad', [(10.45, 4.5), (13.2, 4.5), (13.2, 7.2), (10.45, 7.2)])   # R-05 8.7 m2 target 8.0
eg.room('Flur', [(0.3, 3.2), (13.2, 3.2), (13.2, 4.35), (0.3, 4.35)])   # R-06 17.2 m2 target 10.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-01', on='INT-2', at=4.5, width=0.8, height=2.05)   # R-06 <-> R-01
eg.door('D-02', on='INT-3', at=2.05, width=0.8, height=2.05)   # R-06 <-> R-02
eg.door('D-03', on='INT-5', at=2.6, width=0.8, height=2.05)   # R-06 <-> R-03
eg.door('D-04', on='INT-7', at=2.55, width=0.8, height=2.05)   # R-06 <-> R-04
eg.door('D-05', on='INT-8', at=1.45, width=0.8, height=2.05)   # R-06 <-> R-05
eg.door('D-00', on='EXT-S', at=6.6, width=0.9, height=2.10, external=True, type_name='Eingangstuer')

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=4.5, width=2.4, height=1.4, sill=0.90)   # R-01 needs 3.34 m2
eg.window('F-02', on='EXT-S', at=11.1, width=1.1, height=1.4, sill=0.90)   # R-02 needs 1.53 m2
eg.window('F-03', on='EXT-N', at=10.6, width=1.35, height=1.4, sill=0.90)   # R-03 needs 1.90 m2
eg.window('F-04', on='EXT-N', at=5.5, width=1.35, height=1.4, sill=0.90)   # R-04 needs 1.88 m2

if __name__ == "__main__":
    h.write("out/dreifamilienhaus/model.ifc")

