"""Dreifamilienhaus rev 2 -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/dreifamilienhaus-rev-2.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Dreifamilienhaus rev 2')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (11.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (11.35, 0.15), (11.35, 9.85), thickness=0.3, external=True)
eg.wall('EXT-N', (11.35, 9.85), (0.15, 9.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (7.8, 0.15), (7.8, 4.1), thickness=0.15)
eg.wall('INT-2', (0.15, 4.1), (7.8, 4.1), thickness=0.15)
eg.wall('INT-3', (7.8, 4.1), (11.35, 4.1), thickness=0.15)
eg.wall('INT-4', (4.5, 5.9), (4.5, 9.85), thickness=0.15)
eg.wall('INT-5', (0.15, 5.9), (4.5, 5.9), thickness=0.15)
eg.wall('INT-6', (8.85, 5.9), (8.85, 9.85), thickness=0.15)
eg.wall('INT-7', (4.5, 5.9), (8.85, 5.9), thickness=0.15)
eg.wall('INT-8', (8.85, 5.9), (11.35, 5.9), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (7.7, 0.3), (7.7, 4.0), (0.3, 4.0)])   # R-01 30.2 m2 target 26.0
eg.room('Küche', [(7.9, 0.3), (11.2, 0.3), (11.2, 4.0), (7.9, 4.0)])   # R-02 14.0 m2 target 12.0
eg.room('Schlafzimmer 1', [(0.3, 6.0), (4.4, 6.0), (4.4, 9.7), (0.3, 9.7)])   # R-03 17.2 m2 target 14.0
eg.room('Schlafzimmer 2', [(4.6, 6.0), (8.75, 6.0), (8.75, 9.7), (4.6, 9.7)])   # R-04 17.2 m2 target 14.0
eg.room('Bad', [(8.9, 6.0), (11.2, 6.0), (11.2, 9.7), (8.9, 9.7)])   # R-05 9.9 m2 target 8.0
eg.room('Flur', [(0.3, 4.15), (11.2, 4.15), (11.2, 5.85), (0.3, 5.85)])   # R-06 20.2 m2 target 20.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=5.6, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=3.8, width=0.8, height=2.05)   # R-06 <-> R-01
eg.door('D-02', on='INT-3', at=1.75, width=0.8, height=2.05)   # R-06 <-> R-02
eg.door('D-03', on='INT-5', at=2.15, width=0.8, height=2.05)   # R-06 <-> R-03
eg.door('D-04', on='INT-7', at=2.15, width=0.8, height=2.05)   # R-06 <-> R-04
eg.door('D-05', on='INT-8', at=1.25, width=0.8, height=2.05)   # R-06 <-> R-05

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=3.7, width=2.7, height=1.4, sill=0.9)   # R-01 needs 3.78 m2
eg.window('F-02', on='EXT-E', at=1.95, width=1.25, height=1.4, sill=0.9)   # R-02 needs 1.75 m2
eg.window('F-03', on='EXT-N', at=9.0, width=1.55, height=1.4, sill=0.9)   # R-03 needs 2.15 m2
eg.window('F-04', on='EXT-N', at=4.65, width=1.55, height=1.4, sill=0.9)   # R-04 needs 2.15 m2

if __name__ == "__main__":
    h.write("out/dreifamilienhaus-rev-2/model.ifc")

