"""Neubau -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/neubau.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Neubau')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (13.85, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (13.85, 0.15), (13.85, 13.35), thickness=0.3, external=True)
eg.wall('EXT-N', (13.85, 13.35), (0.15, 13.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 13.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (10.4, 7.4), (10.4, 10.4), thickness=0.15)
eg.wall('INT-2', (10.4, 7.4), (13.85, 7.4), thickness=0.15)
eg.wall('INT-3', (10.4, 10.8), (13.85, 10.8), thickness=0.15)
eg.wall('INT-4', (4.55, 7.4), (4.55, 10.4), thickness=0.15)
eg.wall('INT-5', (4.55, 7.4), (10.4, 7.4), thickness=0.15)
eg.wall('INT-6', (4.55, 10.4), (10.4, 10.4), thickness=0.15)
eg.wall('INT-7', (0.15, 7.4), (4.55, 7.4), thickness=0.15)
eg.wall('INT-8', (4.55, 10.4), (4.55, 13.35), thickness=0.15)
eg.wall('INT-9', (0.15, 6.1), (13.85, 6.1), thickness=0.15)
eg.wall('INT-10', (10.4, 10.8), (10.4, 13.35), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Bad', [(10.45, 7.5), (13.7, 7.5), (13.7, 10.75), (10.45, 10.75)])   # R-01 11.7 m2 target 9.8
eg.room('Küche', [(4.6, 7.5), (10.3, 7.5), (10.3, 10.3), (4.6, 10.3)])   # R-02 17.6 m2 target 14.6
eg.room('Besprechung', [(0.3, 7.5), (4.45, 7.5), (4.45, 13.2), (0.3, 13.2)])   # R-03 26.2 m2 target 22.0
eg.room('Büro', [(0.3, 0.3), (13.7, 0.3), (13.7, 6.0), (0.3, 6.0)])   # R-04 81.5 m2 target 73.2
eg.room('Flur', [(0.3, 6.15), (13.7, 6.15), (13.7, 7.3), (0.3, 7.3)])   # R-05 17.8 m2 target 12.2
eg.room('HWR', [(10.45, 10.9), (13.7, 10.9), (13.7, 13.2), (10.45, 13.2)])   # R-06 8.8 m2 target 7.3
eg.room('Stair', [(4.6, 10.45), (10.3, 10.45), (10.3, 13.2), (4.6, 13.2)])   # R-07 17.3 m2 target 14.6

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=6.85, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=1.7, width=0.8, height=2.05)   # R-05 <-> R-01
eg.door('D-02', on='INT-5', at=2.9, width=0.8, height=2.05)   # R-05 <-> R-02
eg.door('D-03', on='INT-7', at=2.2, width=0.8, height=2.05)   # R-05 <-> R-03
eg.door('D-04', on='INT-9', at=6.85, width=0.8, height=2.05)   # R-05 <-> R-04
eg.door('D-05', on='INT-3', at=1.7, width=0.8, height=2.05)   # R-01 <-> R-06  (plan asked for R-05; rerouted to the neighbour it touches)
eg.door('D-06', on='INT-6', at=2.9, width=0.8, height=2.05)   # R-02 <-> R-07  (plan asked for R-05; rerouted to the neighbour it touches)

# --- windows: sized to the daylight rule, on exterior walls ---
# TODO_AGENT: room R-02 (Küche) has no exterior wall, so it cannot meet the daylight rule; move it to the perimeter
eg.window('F-01', on='EXT-S', at=3.3, width=6.0, height=1.55, sill=0.9)   # R-04 needs 10.19 m2  (short: 9.30 m2 is all this wall can carry)

if __name__ == "__main__":
    h.write("out/neubau/model.ifc")

