"""Dreifamilienhaus rev 2 -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/dreifamilienhaus-rev-2.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Dreifamilienhaus rev 2')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (12.85, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (12.85, 0.15), (12.85, 9.85), thickness=0.3, external=True)
eg.wall('EXT-N', (12.85, 9.85), (0.15, 9.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (0.15, 6.8), (5.3, 6.8), thickness=0.15)
eg.wall('INT-2', (5.3, 0.15), (5.3, 5.0), thickness=0.15)
eg.wall('INT-3', (5.3, 5.0), (5.3, 6.8), thickness=0.15)
eg.wall('INT-4', (5.3, 6.8), (5.3, 9.85), thickness=0.15)
eg.wall('INT-5', (9.05, 0.15), (9.05, 5.0), thickness=0.15)
eg.wall('INT-6', (5.3, 5.0), (7.45, 5.0), thickness=0.15)
eg.wall('INT-7', (7.45, 5.0), (9.05, 5.0), thickness=0.15)
eg.wall('INT-8', (9.05, 5.0), (12.85, 5.0), thickness=0.15)
eg.wall('INT-9', (7.45, 5.0), (7.45, 9.85), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (5.2, 0.3), (5.2, 6.7), (0.3, 6.7)])   # R-01 34.2 m2 target 29.1
eg.room('Küche', [(0.3, 6.9), (5.2, 6.9), (5.2, 9.7), (0.3, 9.7)])   # R-02 15.7 m2 target 13.4
eg.room('Schlafzimmer 1', [(5.4, 0.3), (9.0, 0.3), (9.0, 4.9), (5.4, 4.9)])   # R-03 18.2 m2 target 15.7
eg.room('Schlafzimmer 2', [(9.1, 0.3), (12.7, 0.3), (12.7, 4.9), (9.1, 4.9)])   # R-04 18.4 m2 target 15.7
eg.room('Bad', [(5.4, 5.1), (7.4, 5.1), (7.4, 9.7), (5.4, 9.7)])   # R-05 10.4 m2 target 9.0
eg.room('Flur', [(7.5, 5.1), (12.7, 5.1), (12.7, 9.7), (7.5, 9.7)])   # R-06 26.2 m2 target 22.4

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=6.35, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=2.55, width=0.8, height=2.05)   # R-01 <-> R-02
eg.door('D-02', on='INT-2', at=2.4, width=0.8, height=2.05)   # R-01 <-> R-03
eg.door('D-03', on='INT-5', at=2.4, width=0.8, height=2.05)   # R-03 <-> R-04  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-04', on='INT-3', at=0.9, width=0.8, height=2.05)   # R-01 <-> R-05
eg.door('D-05', on='INT-9', at=2.4, width=0.8, height=2.05)   # R-05 <-> R-06  (plan asked for R-01; rerouted to the neighbour it touches)

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-W', at=6.4, width=3.05, height=1.4, sill=0.9)   # R-01 needs 4.28 m2
eg.window('F-02', on='EXT-N', at=10.1, width=1.4, height=1.4, sill=0.9)   # R-02 needs 1.96 m2
eg.window('F-03', on='EXT-S', at=7.7, width=1.6, height=1.4, sill=0.9)   # R-03 needs 2.27 m2
eg.window('F-04', on='EXT-E', at=2.4, width=1.65, height=1.4, sill=0.9)   # R-04 needs 2.30 m2

if __name__ == "__main__":
    h.write("out/dreifamilienhaus-rev-2/model.ifc")

