"""Familienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/familienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Familienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (15.85, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (15.85, 0.15), (15.85, 8.35), thickness=0.3, external=True)
eg.wall('EXT-N', (15.85, 8.35), (0.15, 8.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 8.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (9.25, 0.15), (9.25, 3.55), thickness=0.15)
eg.wall('INT-2', (0.15, 3.55), (9.25, 3.55), thickness=0.15)
eg.wall('INT-3', (4.8, 4.9), (4.8, 8.35), thickness=0.15)
eg.wall('INT-4', (8.75, 4.9), (8.75, 8.35), thickness=0.15)
eg.wall('INT-5', (4.8, 4.9), (8.75, 4.9), thickness=0.15)
eg.wall('INT-6', (0.15, 4.9), (4.8, 4.9), thickness=0.15)
eg.wall('INT-7', (12.55, 4.9), (12.55, 8.35), thickness=0.15)
eg.wall('INT-8', (8.75, 4.9), (12.55, 4.9), thickness=0.15)
eg.wall('INT-9', (13.15, 0.15), (13.15, 3.55), thickness=0.15)
eg.wall('INT-10', (9.25, 3.55), (13.15, 3.55), thickness=0.15)
eg.wall('INT-11', (12.55, 4.9), (15.85, 4.9), thickness=0.15)
eg.wall('INT-12', (13.15, 3.55), (15.85, 3.55), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (9.2, 0.3), (9.2, 3.45), (0.3, 3.45)])   # R-01 30.9 m2 target 27.0
eg.room('Küche', [(4.9, 5.0), (8.7, 5.0), (8.7, 8.2), (4.9, 8.2)])   # R-02 13.6 m2 target 12.0
eg.room('Elternschlafzimmer', [(0.3, 5.0), (4.7, 5.0), (4.7, 8.2), (0.3, 8.2)])   # R-03 16.0 m2 target 14.0
eg.room('Kinderzimmer 1', [(8.8, 5.0), (12.45, 5.0), (12.45, 8.2), (8.8, 8.2)])   # R-04 13.1 m2 target 11.5
eg.room('Kinderzimmer 2', [(9.3, 0.3), (13.05, 0.3), (13.05, 3.45), (9.3, 3.45)])   # R-05 13.3 m2 target 11.5
eg.room('Büro', [(12.6, 5.0), (15.7, 5.0), (15.7, 8.2), (12.6, 8.2)])   # R-06 11.4 m2 target 10.0
eg.room('Bad', [(13.2, 0.3), (15.7, 0.3), (15.7, 3.45), (13.2, 3.45)])   # R-07 9.2 m2 target 8.0
eg.room('Flur', [(0.3, 3.6), (15.7, 3.6), (15.7, 4.85), (0.3, 4.85)])   # R-08 21.2 m2 target 11.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=7.85, width=1.01, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=4.55, width=0.885, height=2.05)   # R-08 <-> R-01
eg.door('D-02', on='INT-5', at=2.0, width=0.885, height=2.05)   # R-08 <-> R-02
eg.door('D-03', on='INT-6', at=2.3, width=0.885, height=2.05)   # R-08 <-> R-03
eg.door('D-04', on='INT-8', at=1.9, width=0.885, height=2.05)   # R-08 <-> R-04
eg.door('D-05', on='INT-10', at=1.95, width=0.885, height=2.05)   # R-08 <-> R-05
eg.door('D-06', on='INT-11', at=1.65, width=0.885, height=2.05)   # R-08 <-> R-06
eg.door('D-07', on='INT-12', at=1.35, width=0.885, height=2.05)   # R-08 <-> R-07

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=4.55, width=2.75, height=1.4, sill=0.9)   # R-01 needs 3.87 m2
eg.window('F-02', on='EXT-N', at=9.05, width=1.2, height=1.4, sill=0.9)   # R-02 needs 1.70 m2
eg.window('F-03', on='EXT-N', at=13.4, width=1.45, height=1.4, sill=0.9)   # R-03 needs 2.01 m2
eg.window('F-04', on='EXT-N', at=5.2, width=1.15, height=1.4, sill=0.9)   # R-04 needs 1.64 m2
eg.window('F-05', on='EXT-S', at=11.05, width=1.2, height=1.4, sill=0.9)   # R-05 needs 1.66 m2
eg.window('F-06', on='EXT-E', at=6.45, width=1.0, height=1.4, sill=0.9)   # R-06 needs 1.42 m2

if __name__ == "__main__":
    h.write("out/familienhaus/model.ifc")

