"""Familienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/familienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Familienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (15.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (15.35, 0.15), (15.35, 8.85), thickness=0.3, external=True)
eg.wall('EXT-N', (15.35, 8.85), (0.15, 8.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 8.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (7.75, 0.15), (7.75, 3.8), thickness=0.15)
eg.wall('INT-2', (0.15, 3.8), (7.75, 3.8), thickness=0.15)
eg.wall('INT-3', (9.0, 5.15), (9.0, 8.85), thickness=0.15)
eg.wall('INT-4', (12.8, 5.15), (12.8, 8.85), thickness=0.15)
eg.wall('INT-5', (9.0, 5.15), (12.8, 5.15), thickness=0.15)
eg.wall('INT-6', (4.6, 5.15), (4.6, 8.85), thickness=0.15)
eg.wall('INT-7', (0.15, 5.15), (4.6, 5.15), thickness=0.15)
eg.wall('INT-8', (4.6, 5.15), (9.0, 5.15), thickness=0.15)
eg.wall('INT-9', (11.85, 0.15), (11.85, 3.8), thickness=0.15)
eg.wall('INT-10', (7.75, 3.8), (11.85, 3.8), thickness=0.15)
eg.wall('INT-11', (12.8, 5.15), (15.35, 5.15), thickness=0.15)
eg.wall('INT-12', (11.85, 3.8), (15.35, 3.8), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (7.65, 0.3), (7.65, 3.7), (0.3, 3.7)])   # R-01 27.7 m2 target 26.0
eg.room('Küche', [(9.05, 5.2), (12.7, 5.2), (12.7, 8.7), (9.05, 8.7)])   # R-02 14.1 m2 target 12.0
eg.room('Schlafzimmer 1', [(0.3, 5.2), (4.5, 5.2), (4.5, 8.7), (0.3, 8.7)])   # R-03 16.5 m2 target 14.0
eg.room('Schlafzimmer 2', [(4.65, 5.2), (8.9, 5.2), (8.9, 8.7), (4.65, 8.7)])   # R-04 16.3 m2 target 14.0
eg.room('Schlafzimmer 3', [(7.8, 0.3), (11.75, 0.3), (11.75, 3.7), (7.8, 3.7)])   # R-05 15.0 m2 target 14.0
eg.room('Bad', [(12.9, 5.2), (15.2, 5.2), (15.2, 8.7), (12.9, 8.7)])   # R-06 9.4 m2 target 8.0
eg.room('Büro', [(11.9, 0.3), (15.2, 0.3), (15.2, 3.7), (11.9, 3.7)])   # R-07 12.8 m2 target 12.0
eg.room('Flur', [(0.3, 3.9), (15.2, 3.9), (15.2, 5.1), (0.3, 5.1)])   # R-08 20.5 m2 target 10.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=7.6, width=1.01, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=3.8, width=0.885, height=2.05)   # R-08 <-> R-01
eg.door('D-02', on='INT-5', at=1.9, width=0.885, height=2.05)   # R-08 <-> R-02
eg.door('D-03', on='INT-7', at=2.2, width=0.885, height=2.05)   # R-08 <-> R-03
eg.door('D-04', on='INT-8', at=2.2, width=0.885, height=2.05)   # R-08 <-> R-04
eg.door('D-05', on='INT-10', at=2.05, width=0.885, height=2.05)   # R-08 <-> R-05
eg.door('D-06', on='INT-11', at=1.25, width=0.885, height=2.05)   # R-08 <-> R-06
eg.door('D-07', on='INT-12', at=1.75, width=0.885, height=2.05)   # R-08 <-> R-07

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=3.8, width=2.5, height=1.4, sill=0.9)   # R-01 needs 3.47 m2
eg.window('F-02', on='EXT-N', at=4.45, width=1.25, height=1.4, sill=0.9)   # R-02 needs 1.76 m2
eg.window('F-03', on='EXT-N', at=13.0, width=1.45, height=1.4, sill=0.9)   # R-03 needs 2.06 m2
eg.window('F-04', on='EXT-N', at=8.55, width=1.45, height=1.4, sill=0.9)   # R-04 needs 2.03 m2
eg.window('F-05', on='EXT-S', at=9.65, width=1.35, height=1.4, sill=0.9)   # R-05 needs 1.87 m2
eg.window('F-06', on='EXT-E', at=1.8, width=1.15, height=1.4, sill=0.9)   # R-07 needs 1.60 m2

if __name__ == "__main__":
    h.write("out/familienhaus/model.ifc")

