"""Neubau -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/neubau.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Neubau')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (14.85, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (14.85, 0.15), (14.85, 11.35), thickness=0.3, external=True)
eg.wall('EXT-N', (14.85, 11.35), (0.15, 11.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 11.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (0.15, 2.5), (4.6, 2.5), thickness=0.15)
eg.wall('INT-2', (4.6, 0.15), (4.6, 2.5), thickness=0.15)
eg.wall('INT-3', (0.15, 6.05), (4.6, 6.05), thickness=0.15)
eg.wall('INT-4', (4.6, 2.5), (4.6, 6.05), thickness=0.15)
eg.wall('INT-5', (4.6, 6.05), (4.6, 7.8), thickness=0.15)
eg.wall('INT-6', (4.6, 7.8), (4.6, 11.35), thickness=0.15)
eg.wall('INT-7', (4.6, 7.8), (8.25, 7.8), thickness=0.15)
eg.wall('INT-8', (8.25, 7.8), (10.45, 7.8), thickness=0.15)
eg.wall('INT-9', (10.45, 7.8), (14.85, 7.8), thickness=0.15)
eg.wall('INT-10', (8.25, 7.8), (8.25, 11.35), thickness=0.15)
eg.wall('INT-11', (10.45, 7.8), (10.45, 11.35), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Bad', [(0.3, 0.3), (4.5, 0.3), (4.5, 2.4), (0.3, 2.4)])   # R-01 10.5 m2 target 9.0
eg.room('Küche', [(0.3, 2.6), (4.5, 2.6), (4.5, 5.95), (0.3, 5.95)])   # R-02 15.8 m2 target 13.4
eg.room('Besprechung', [(0.3, 6.1), (4.5, 6.1), (4.5, 11.2), (0.3, 11.2)])   # R-03 23.6 m2 target 20.2
eg.room('Büro', [(4.65, 0.3), (14.7, 0.3), (14.7, 7.7), (4.65, 7.7)])   # R-04 78.4 m2 target 67.2
eg.room('Flur', [(4.65, 7.9), (8.2, 7.9), (8.2, 11.2), (4.65, 11.2)])   # R-05 13.0 m2 target 11.2
eg.room('HWR', [(8.3, 7.9), (10.35, 7.9), (10.35, 11.2), (8.3, 11.2)])   # R-06 7.8 m2 target 6.7
eg.room('Stair', [(10.5, 7.9), (14.7, 7.9), (14.7, 11.2), (10.5, 11.2)])   # R-07 15.6 m2 target 13.4

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=7.35, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=2.2, width=0.8, height=2.05)   # R-01 <-> R-02
eg.door('D-02', on='INT-3', at=2.2, width=0.8, height=2.05)   # R-02 <-> R-03  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-03', on='INT-2', at=1.2, width=0.8, height=2.05)   # R-01 <-> R-04
eg.door('D-04', on='INT-7', at=1.8, width=0.8, height=2.05)   # R-04 <-> R-05  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-05', on='INT-10', at=1.75, width=0.8, height=2.05)   # R-05 <-> R-06  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-06', on='INT-9', at=2.2, width=0.8, height=2.05)   # R-04 <-> R-07  (plan asked for R-01; rerouted to the neighbour it touches)

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-W', at=7.05, width=1.4, height=1.4, sill=0.9)   # R-02 needs 1.97 m2
eg.window('F-02', on='EXT-S', at=11.15, width=6.5, height=1.51, sill=0.9)   # R-04 needs 9.80 m2  (narrowed to 6.50 m, height raised to 1.51 m to keep the area)

if __name__ == "__main__":
    h.write("out/neubau/model.ifc")

