"""Neubau -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/neubau.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Neubau')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (13.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (13.35, 0.15), (13.35, 11.35), thickness=0.3, external=True)
eg.wall('EXT-N', (13.35, 11.35), (0.15, 11.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 11.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (10.05, 6.4), (13.35, 6.4), thickness=0.15)
eg.wall('INT-2', (10.05, 9.25), (13.35, 9.25), thickness=0.15)
eg.wall('INT-3', (10.05, 6.4), (10.05, 9.25), thickness=0.15)
eg.wall('INT-4', (4.4, 6.4), (4.4, 11.35), thickness=0.15)
eg.wall('INT-5', (4.4, 6.4), (7.2, 6.4), thickness=0.15)
eg.wall('INT-6', (7.2, 6.4), (7.2, 11.35), thickness=0.15)
eg.wall('INT-7', (0.15, 6.4), (4.4, 6.4), thickness=0.15)
eg.wall('INT-8', (0.15, 5.1), (13.35, 5.1), thickness=0.15)
eg.wall('INT-9', (7.2, 6.4), (10.05, 6.4), thickness=0.15)
eg.wall('INT-10', (10.05, 9.25), (10.05, 11.35), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Bad', [(10.1, 6.5), (13.2, 6.5), (13.2, 9.2), (10.1, 9.2)])   # R-01 9.4 m2 target 8.0
eg.room('Küche', [(4.5, 6.5), (7.1, 6.5), (7.1, 11.2), (4.5, 11.2)])   # R-02 13.9 m2 target 12.0
eg.room('Besprechung', [(0.3, 6.5), (4.3, 6.5), (4.3, 11.2), (0.3, 11.2)])   # R-03 21.0 m2 target 18.0
eg.room('Büro', [(0.3, 0.3), (13.2, 0.3), (13.2, 5.0), (0.3, 5.0)])   # R-04 65.3 m2 target 60.0
eg.room('Flur', [(0.3, 5.15), (13.2, 5.15), (13.2, 6.35), (0.3, 6.35)])   # R-05 17.2 m2 target 10.0
eg.room('HWR', [(10.1, 9.3), (13.2, 9.3), (13.2, 11.2), (10.1, 11.2)])   # R-06 6.9 m2 target 6.0
eg.room('Stair', [(7.3, 6.5), (10.0, 6.5), (10.0, 11.2), (7.3, 11.2)])   # R-07 14.1 m2 target 12.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=6.6, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=1.65, width=0.8, height=2.05)   # R-05 <-> R-01
eg.door('D-02', on='INT-5', at=1.4, width=0.8, height=2.05)   # R-05 <-> R-02
eg.door('D-03', on='INT-7', at=2.1, width=0.8, height=2.05)   # R-05 <-> R-03
eg.door('D-04', on='INT-8', at=6.6, width=0.8, height=2.05)   # R-05 <-> R-04
eg.door('D-05', on='INT-2', at=1.65, width=0.8, height=2.05)   # R-01 <-> R-06  (plan asked for R-05; rerouted to the neighbour it touches)
eg.door('D-06', on='INT-9', at=1.45, width=0.8, height=2.05)   # R-05 <-> R-07

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-N', at=7.55, width=1.25, height=1.4, sill=0.9)   # R-02 needs 1.73 m2
eg.window('F-02', on='EXT-S', at=3.15, width=5.75, height=1.42, sill=0.9)   # R-04 needs 8.17 m2  (short: 8.16 m2 is all this wall can carry)

if __name__ == "__main__":
    h.write("out/neubau/model.ifc")

