"""Dreifamilienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/dreifamilienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Dreifamilienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (11.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (11.35, 0.15), (11.35, 8.35), thickness=0.3, external=True)
eg.wall('EXT-N', (11.35, 8.35), (0.15, 8.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 8.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (4.1, 0.15), (4.1, 4.6), thickness=0.15)
eg.wall('INT-2', (4.1, 4.6), (4.1, 8.35), thickness=0.15)
eg.wall('INT-3', (7.45, 0.15), (7.45, 4.6), thickness=0.15)
eg.wall('INT-4', (4.1, 4.6), (7.45, 4.6), thickness=0.15)
eg.wall('INT-5', (7.45, 4.6), (8.7, 4.6), thickness=0.15)
eg.wall('INT-6', (8.7, 4.6), (11.35, 4.6), thickness=0.15)
eg.wall('INT-7', (8.7, 4.6), (8.7, 8.35), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (4.0, 0.3), (4.0, 8.2), (0.3, 8.2)])   # R-01 32.4 m2 target 29.1
eg.room('Küche', [(4.15, 0.3), (7.4, 0.3), (7.4, 4.5), (4.15, 4.5)])   # R-02 14.9 m2 target 13.4
eg.room('Schlafzimmer 1', [(7.5, 0.3), (11.2, 0.3), (11.2, 4.5), (7.5, 4.5)])   # R-03 17.4 m2 target 15.7
eg.room('Schlafzimmer 2', [(4.15, 4.65), (8.6, 4.65), (8.6, 8.2), (4.15, 8.2)])   # R-04 17.2 m2 target 15.7
eg.room('Bad', [(8.75, 4.65), (11.2, 4.65), (11.2, 8.2), (8.75, 8.2)])   # R-05 9.9 m2 target 9.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=5.6, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=2.2, width=0.8, height=2.05)   # R-01 <-> R-02
eg.door('D-02', on='INT-3', at=2.2, width=0.8, height=2.05)   # R-02 <-> R-03  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-03', on='INT-2', at=1.9, width=0.8, height=2.05)   # R-01 <-> R-04
eg.door('D-04', on='INT-7', at=1.9, width=0.8, height=2.05)   # R-04 <-> R-05  (plan asked for R-01; rerouted to the neighbour it touches)

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-W', at=4.1, width=2.9, height=1.4, sill=0.9)   # R-01 needs 4.05 m2
eg.window('F-02', on='EXT-S', at=6.55, width=0.85, height=1.55, sill=0.9)   # R-02 needs 1.86 m2  (short: 1.32 m2 is all this wall can carry)
eg.window('F-03', on='EXT-E', at=2.2, width=1.55, height=1.4, sill=0.9)   # R-03 needs 2.17 m2
eg.window('F-04', on='EXT-N', at=4.95, width=1.55, height=1.4, sill=0.9)   # R-04 needs 2.16 m2

if __name__ == "__main__":
    h.write("out/dreifamilienhaus/model.ifc")

