"""Coworking Studio -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/coworking-studio.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Coworking Studio')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.7)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (11.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (11.35, 0.15), (11.35, 9.85), thickness=0.3, external=True)
eg.wall('EXT-N', (11.35, 9.85), (0.15, 9.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (0.15, 4.3), (11.35, 4.3), thickness=0.15)
eg.wall('INT-2', (5.45, 5.65), (5.45, 9.85), thickness=0.15)
eg.wall('INT-3', (0.15, 5.65), (5.45, 5.65), thickness=0.15)
eg.wall('INT-4', (9.0, 5.65), (9.0, 9.85), thickness=0.15)
eg.wall('INT-5', (9.0, 5.65), (11.35, 5.65), thickness=0.15)
eg.wall('INT-6', (5.45, 5.65), (9.0, 5.65), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Studio', [(0.3, 0.3), (11.2, 0.3), (11.2, 4.2), (0.3, 4.2)])   # R-01 46.5 m2 target 50.0
eg.room('Conference', [(0.3, 5.7), (5.35, 5.7), (5.35, 9.7), (0.3, 9.7)])   # R-02 22.3 m2 target 18.0
eg.room('Washroom', [(9.05, 5.7), (11.2, 5.7), (11.2, 9.7), (9.05, 9.7)])   # R-03 9.9 m2 target 8.0
eg.room('Kitchenette', [(5.5, 5.7), (8.9, 5.7), (8.9, 9.7), (5.5, 9.7)])   # R-04 14.9 m2 target 12.0
eg.room('Flur', [(0.3, 4.4), (11.2, 4.4), (11.2, 5.6), (0.3, 5.6)])   # R-05 15.1 m2 target 10.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=5.6, width=1.01, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-1', at=5.6, width=0.885, height=2.05)   # R-05 <-> R-01
eg.door('D-02', on='INT-3', at=2.65, width=0.885, height=2.05)   # R-05 <-> R-02
eg.door('D-03', on='INT-5', at=1.15, width=0.885, height=2.05)   # R-05 <-> R-03
eg.door('D-04', on='INT-6', at=1.75, width=0.885, height=2.05)   # R-05 <-> R-04

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=2.9, width=4.15, height=1.4, sill=0.9)   # R-01 needs 5.81 m2
eg.window('F-02', on='EXT-N', at=4.1, width=1.35, height=1.4, sill=0.9)   # R-04 needs 1.86 m2

if __name__ == "__main__":
    h.write("out/coworking-studio/model.ifc")

