"""Dreifamilienhaus rev 2 -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/dreifamilienhaus-rev-2.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Dreifamilienhaus rev 2')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (13.85, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (13.85, 0.15), (13.85, 7.85), thickness=0.3, external=True)
eg.wall('EXT-N', (13.85, 7.85), (0.15, 7.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 7.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (9.5, 0.15), (9.5, 3.25), thickness=0.15)
eg.wall('INT-2', (0.15, 3.25), (9.5, 3.25), thickness=0.15)
eg.wall('INT-3', (9.5, 3.25), (13.85, 3.25), thickness=0.15)
eg.wall('INT-4', (5.5, 4.75), (5.5, 7.85), thickness=0.15)
eg.wall('INT-5', (0.15, 4.75), (5.5, 4.75), thickness=0.15)
eg.wall('INT-6', (10.8, 4.75), (10.8, 7.85), thickness=0.15)
eg.wall('INT-7', (5.5, 4.75), (10.8, 4.75), thickness=0.15)
eg.wall('INT-8', (10.8, 4.75), (13.85, 4.75), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (9.4, 0.3), (9.4, 3.15), (0.3, 3.15)])   # R-01 29.0 m2 target 26.0
eg.room('Küche', [(9.55, 0.3), (13.7, 0.3), (13.7, 3.15), (9.55, 3.15)])   # R-02 13.5 m2 target 12.0
eg.room('Schlafzimmer 1', [(0.3, 4.8), (5.4, 4.8), (5.4, 7.7), (0.3, 7.7)])   # R-03 16.6 m2 target 14.0
eg.room('Schlafzimmer 2', [(5.6, 4.8), (10.75, 4.8), (10.75, 7.7), (5.6, 7.7)])   # R-04 16.4 m2 target 14.0
eg.room('Bad', [(10.9, 4.8), (13.7, 4.8), (13.7, 7.7), (10.9, 7.7)])   # R-05 9.5 m2 target 8.0
eg.room('Flur', [(0.3, 3.3), (13.7, 3.3), (13.7, 4.7), (0.3, 4.7)])   # R-06 20.5 m2 target 20.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=6.85, width=0.9, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=4.65, width=0.8, height=2.05)   # R-06 <-> R-01
eg.door('D-02', on='INT-3', at=2.15, width=0.8, height=2.05)   # R-06 <-> R-02
eg.door('D-03', on='INT-5', at=2.65, width=0.8, height=2.05)   # R-06 <-> R-03
eg.door('D-04', on='INT-7', at=2.65, width=0.8, height=2.05)   # R-06 <-> R-04
eg.door('D-05', on='INT-8', at=1.5, width=0.8, height=2.05)   # R-06 <-> R-05

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=4.65, width=2.6, height=1.4, sill=0.9)   # R-01 needs 3.62 m2
eg.window('F-02', on='EXT-S', at=11.5, width=1.2, height=1.4, sill=0.9)   # R-02 needs 1.69 m2
eg.window('F-03', on='EXT-N', at=11.0, width=1.5, height=1.4, sill=0.9)   # R-03 needs 2.07 m2
eg.window('F-04', on='EXT-N', at=5.7, width=1.45, height=1.4, sill=0.9)   # R-04 needs 2.05 m2

if __name__ == "__main__":
    h.write("out/dreifamilienhaus-rev-2/model.ifc")

