"""Familienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/familienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Familienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (12.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (12.35, 0.15), (12.35, 10.85), thickness=0.3, external=True)
eg.wall('EXT-N', (12.35, 10.85), (0.15, 10.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 10.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (6.25, 0.15), (6.25, 4.8), thickness=0.15)
eg.wall('INT-2', (0.15, 4.8), (6.25, 4.8), thickness=0.15)
eg.wall('INT-3', (7.25, 6.15), (7.25, 10.85), thickness=0.15)
eg.wall('INT-4', (10.3, 6.15), (10.3, 10.85), thickness=0.15)
eg.wall('INT-5', (7.25, 6.15), (10.3, 6.15), thickness=0.15)
eg.wall('INT-6', (3.7, 6.15), (3.7, 10.85), thickness=0.15)
eg.wall('INT-7', (0.15, 6.15), (3.7, 6.15), thickness=0.15)
eg.wall('INT-8', (3.7, 6.15), (7.25, 6.15), thickness=0.15)
eg.wall('INT-9', (9.55, 0.15), (9.55, 4.8), thickness=0.15)
eg.wall('INT-10', (6.25, 4.8), (9.55, 4.8), thickness=0.15)
eg.wall('INT-11', (10.3, 6.15), (12.35, 6.15), thickness=0.15)
eg.wall('INT-12', (9.55, 4.8), (12.35, 4.8), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (6.15, 0.3), (6.15, 4.7), (0.3, 4.7)])   # R-01 28.4 m2 target 26.0
eg.room('Küche', [(7.3, 6.2), (10.25, 6.2), (10.25, 10.7), (7.3, 10.7)])   # R-02 14.3 m2 target 12.0
eg.room('Schlafzimmer 1', [(0.3, 6.2), (3.6, 6.2), (3.6, 10.7), (0.3, 10.7)])   # R-03 16.7 m2 target 14.0
eg.room('Schlafzimmer 2', [(3.8, 6.2), (7.2, 6.2), (7.2, 10.7), (3.8, 10.7)])   # R-04 16.7 m2 target 14.0
eg.room('Schlafzimmer 3', [(6.3, 0.3), (9.5, 0.3), (9.5, 4.7), (6.3, 4.7)])   # R-05 15.3 m2 target 14.0
eg.room('Bad', [(10.4, 6.2), (12.2, 6.2), (12.2, 10.7), (10.4, 10.7)])   # R-06 9.6 m2 target 8.0
eg.room('Büro', [(9.6, 0.3), (12.2, 0.3), (12.2, 4.7), (9.6, 4.7)])   # R-07 13.0 m2 target 12.0
eg.room('Flur', [(0.3, 4.9), (12.2, 4.9), (12.2, 6.1), (0.3, 6.1)])   # R-08 16.5 m2 target 10.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-01', on='INT-2', at=3.05, width=0.885, height=2.05)   # R-08 <-> R-01
eg.door('D-02', on='INT-5', at=1.55, width=0.885, height=2.05)   # R-08 <-> R-02
eg.door('D-03', on='INT-7', at=1.8, width=0.885, height=2.05)   # R-08 <-> R-03
eg.door('D-04', on='INT-8', at=1.75, width=0.885, height=2.05)   # R-08 <-> R-04
eg.door('D-05', on='INT-10', at=1.65, width=0.885, height=2.05)   # R-08 <-> R-05
eg.door('D-06', on='INT-11', at=1.0, width=0.885, height=2.05)   # R-08 <-> R-06
eg.door('D-07', on='INT-12', at=1.4, width=0.885, height=2.05)   # R-08 <-> R-07
eg.door('D-00', on='EXT-S', at=6.1, width=1.01, height=2.10, external=True, type_name='Eingangstuer')

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=3.05, width=2.55, height=1.4, sill=0.90)   # R-01 needs 3.55 m2
eg.window('F-02', on='EXT-N', at=3.55, width=1.3, height=1.4, sill=0.90)   # R-02 needs 1.79 m2
eg.window('F-03', on='EXT-W', at=2.35, width=1.5, height=1.4, sill=0.90)   # R-03 needs 2.09 m2
eg.window('F-04', on='EXT-N', at=6.9, width=1.5, height=1.4, sill=0.90)   # R-04 needs 2.09 m2
eg.window('F-05', on='EXT-S', at=7.75, width=1.35, height=1.4, sill=0.90)   # R-05 needs 1.92 m2
eg.window('F-06', on='EXT-E', at=2.3, width=1.15, height=1.4, sill=0.90)   # R-07 needs 1.63 m2

if __name__ == "__main__":
    h.write("out/familienhaus/model.ifc")

