"""Familienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/familienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Familienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (13.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (13.35, 0.15), (13.35, 11.35), thickness=0.3, external=True)
eg.wall('EXT-N', (13.35, 11.35), (0.15, 11.35), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 11.35), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (7.55, 0.15), (7.55, 5.1), thickness=0.15)
eg.wall('INT-2', (0.15, 5.1), (7.55, 5.1), thickness=0.15)
eg.wall('INT-3', (3.8, 6.4), (3.8, 11.35), thickness=0.15)
eg.wall('INT-4', (7.0, 6.4), (7.0, 11.35), thickness=0.15)
eg.wall('INT-5', (3.8, 6.4), (7.0, 6.4), thickness=0.15)
eg.wall('INT-6', (0.15, 6.4), (3.8, 6.4), thickness=0.15)
eg.wall('INT-7', (10.7, 0.15), (10.7, 5.05), thickness=0.15)
eg.wall('INT-8', (7.55, 5.1), (10.7, 5.1), thickness=0.15)
eg.wall('INT-9', (9.95, 6.4), (9.95, 9.25), thickness=0.15)
eg.wall('INT-10', (9.95, 9.25), (9.95, 11.35), thickness=0.15)
eg.wall('INT-11', (7.0, 6.4), (9.95, 6.4), thickness=0.15)
eg.wall('INT-12', (9.95, 9.25), (13.35, 9.25), thickness=0.15)
eg.wall('INT-13', (9.95, 6.4), (13.35, 6.4), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (7.45, 0.3), (7.45, 5.0), (0.3, 5.0)])   # R-01 36.6 m2 target 28.0
eg.room('Küche (Essküche)', [(3.9, 6.5), (6.9, 6.5), (6.9, 11.2), (3.9, 11.2)])   # R-02 15.8 m2 target 13.0
eg.room('Elternschlafzimmer', [(0.3, 6.5), (3.7, 6.5), (3.7, 11.2), (0.3, 11.2)])   # R-03 18.1 m2 target 15.0
eg.room('Kinderzimmer 1', [(7.6, 0.3), (10.6, 0.3), (10.6, 5.0), (7.6, 5.0)])   # R-04 15.6 m2 target 12.0
eg.room('Kinderzimmer 2', [(7.1, 6.5), (9.9, 6.5), (9.9, 11.2), (7.1, 11.2)])   # R-05 14.6 m2 target 12.0
eg.room('Bad', [(10.0, 6.5), (13.2, 6.5), (13.2, 9.2), (10.0, 9.2)])   # R-06 9.7 m2 target 8.0
eg.room('Büro', [(10.75, 0.3), (13.2, 0.3), (13.2, 4.95), (10.75, 4.95)])   # R-07 13.0 m2 target 10.0
eg.room('Hausarbeitsraum', [(10.0, 9.3), (13.2, 9.3), (13.2, 11.2), (10.0, 11.2)])   # R-08 7.1 m2 target 6.0
eg.room('Diele / Flur', [(0.3, 5.15), (13.2, 5.15), (13.2, 6.35), (0.3, 6.35)])   # R-09 17.2 m2 target 14.0

# --- doors: one per adjacency declared in the plan ---
eg.door('D-00', on='EXT-S', at=6.6, width=1.01, height=2.10, external=True, type_name='Eingangstuer')
eg.door('D-01', on='INT-2', at=3.7, width=0.885, height=2.05)   # R-09 <-> R-01
eg.door('D-02', on='INT-5', at=1.6, width=0.885, height=2.05)   # R-09 <-> R-02
eg.door('D-03', on='INT-6', at=1.8, width=0.885, height=2.05)   # R-09 <-> R-03
eg.door('D-04', on='INT-8', at=1.55, width=0.885, height=2.05)   # R-09 <-> R-04
eg.door('D-05', on='INT-11', at=1.45, width=0.885, height=2.05)   # R-09 <-> R-05
eg.door('D-06', on='INT-13', at=1.7, width=0.885, height=2.05)   # R-09 <-> R-06
eg.door('D-07', on='INT-7', at=2.45, width=0.885, height=2.05)   # R-04 <-> R-07  (plan asked for R-09; rerouted to the neighbour it touches)
eg.door('D-08', on='INT-12', at=1.7, width=0.885, height=2.05)   # R-06 <-> R-08  (plan asked for R-09; rerouted to the neighbour it touches)
eg.door('D-09', on='INT-12', at=2.7, width=0.885, height=2.05)   # R-06 <-> R-08  (plan asked for R-02; rerouted to the neighbour it touches)

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-S', at=3.7, width=3.25, height=1.4, sill=0.9)   # R-01 needs 4.58 m2
eg.window('F-02', on='EXT-N', at=7.95, width=1.4, height=1.4, sill=0.9)   # R-02 needs 1.98 m2
eg.window('F-03', on='EXT-W', at=2.45, width=1.6, height=1.4, sill=0.9)   # R-03 needs 2.26 m2
eg.window('F-04', on='EXT-S', at=8.95, width=1.4, height=1.4, sill=0.9)   # R-04 needs 1.95 m2
eg.window('F-05', on='EXT-N', at=4.9, width=1.3, height=1.4, sill=0.9)   # R-05 needs 1.83 m2
eg.window('F-06', on='EXT-E', at=2.45, width=1.15, height=1.4, sill=0.9)   # R-07 needs 1.62 m2

if __name__ == "__main__":
    h.write("out/familienhaus/model.ifc")

