"""Familienhaus -- generated by recognition.translate. Do not edit by hand.

Regenerate with:  uv run recognition build plans/familienhaus.json

Every coordinate below was computed from the ArchitectPlan by deterministic code,
not written by a language model. Change the plan, not this file.
"""
from recognition.design import House

h = House('Familienhaus')
eg = h.storey('Erdgeschoss', elevation=0.0, height=2.5)


# --- walls: external envelope, then partitions between rooms ---
eg.wall('EXT-S', (0.15, 0.15), (13.35, 0.15), thickness=0.3, external=True)
eg.wall('EXT-E', (13.35, 0.15), (13.35, 9.85), thickness=0.3, external=True)
eg.wall('EXT-N', (13.35, 9.85), (0.15, 9.85), thickness=0.3, external=True)
eg.wall('EXT-W', (0.15, 9.85), (0.15, 0.15), thickness=0.3, external=True)
eg.wall('INT-1', (0.15, 6.8), (5.15, 6.8), thickness=0.15)
eg.wall('INT-2', (5.15, 0.15), (5.15, 4.55), thickness=0.15)
eg.wall('INT-3', (5.15, 4.55), (5.15, 6.8), thickness=0.15)
eg.wall('INT-4', (5.15, 6.8), (5.15, 9.85), thickness=0.15)
eg.wall('INT-5', (9.25, 0.15), (9.25, 4.55), thickness=0.15)
eg.wall('INT-6', (5.15, 4.55), (8.55, 4.55), thickness=0.15)
eg.wall('INT-7', (9.25, 4.55), (13.35, 4.55), thickness=0.15)
eg.wall('INT-8', (8.55, 4.55), (8.55, 6.65), thickness=0.15)
eg.wall('INT-9', (8.55, 6.65), (8.55, 9.85), thickness=0.15)
eg.wall('INT-10', (8.55, 6.65), (13.35, 6.65), thickness=0.15)

# --- rooms: floor outlines inset to the inside face of their walls ---
eg.room('Wohnen', [(0.3, 0.3), (5.05, 0.3), (5.05, 6.7), (0.3, 6.7)])   # R-01 33.2 m2 target 29.1
eg.room('Küche', [(0.3, 6.9), (5.05, 6.9), (5.05, 9.7), (0.3, 9.7)])   # R-02 15.2 m2 target 13.4
eg.room('Schlafzimmer 1', [(5.2, 0.3), (9.2, 0.3), (9.2, 4.45), (5.2, 4.45)])   # R-03 18.0 m2 target 15.7
eg.room('Schlafzimmer 2', [(9.3, 0.3), (13.2, 0.3), (13.2, 4.45), (9.3, 4.45)])   # R-04 18.0 m2 target 15.7
eg.room('Schlafzimmer 3', [(5.2, 4.6), (8.5, 4.6), (8.5, 9.7), (5.2, 9.7)])   # R-05 18.0 m2 target 15.7
eg.room('Bad', [(8.6, 4.6), (13.2, 4.6), (13.2, 6.6), (8.6, 6.6)])   # R-06 10.1 m2 target 9.0
eg.room('Büro', [(8.6, 6.7), (13.2, 6.7), (13.2, 9.7), (8.6, 9.7)])   # R-07 15.4 m2 target 13.4

# --- doors: one per adjacency declared in the plan ---
eg.door('D-01', on='INT-1', at=2.5, width=0.885, height=2.05)   # R-01 <-> R-02
eg.door('D-02', on='INT-2', at=2.2, width=0.885, height=2.05)   # R-01 <-> R-03
eg.door('D-03', on='INT-5', at=2.2, width=0.885, height=2.05)   # R-03 <-> R-04  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-04', on='INT-3', at=1.1, width=0.885, height=2.05)   # R-01 <-> R-05
eg.door('D-05', on='INT-10', at=2.4, width=0.885, height=2.05)   # R-07 <-> R-06  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-06', on='INT-10', at=2.4, width=0.885, height=2.05)   # R-06 <-> R-07  (plan asked for R-01; rerouted to the neighbour it touches)
eg.door('D-00', on='EXT-S', at=6.6, width=1.01, height=2.10, external=True, type_name='Eingangstuer')

# --- windows: sized to the daylight rule, on exterior walls ---
eg.window('F-01', on='EXT-W', at=6.4, width=2.95, height=1.4, sill=0.90)   # R-01 needs 4.16 m2
eg.window('F-02', on='EXT-N', at=10.7, width=1.35, height=1.4, sill=0.90)   # R-02 needs 1.91 m2
eg.window('F-03', on='EXT-S', at=7.05, width=1.6, height=1.4, sill=0.90)   # R-03 needs 2.25 m2
eg.window('F-04', on='EXT-E', at=2.2, width=1.6, height=1.4, sill=0.90)   # R-04 needs 2.25 m2
eg.window('F-05', on='EXT-N', at=6.5, width=1.6, height=1.4, sill=0.90)   # R-05 needs 2.25 m2
eg.window('F-06', on='EXT-N', at=2.4, width=1.35, height=1.4, sill=0.90)   # R-07 needs 1.92 m2

if __name__ == "__main__":
    h.write("out/familienhaus/model.ifc")

